spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-open?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 1107ABCabc1111
      # mysql-connector >= 6.x: com.mysql.cj.jdbc.Driver
      # mysql-connector <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池最大连接数 默认10
      maximum-pool-size: 10
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: BJ
        # namespace: 56116141-d837-4d15-8842-94e153bb6cfb
  profiles:
    include: common
    #active: dev

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /mall

#设置日志级别
logging:
  level:
    com.platform: debug
  config: classpath:config/logback-spring.xml
  file:
    path: /data/logs

keyGenerator:
  snowflake:
    workerId: 1 #工作节点ID，每个实例都要设置不同的值，范围：0-31
    datacenterId: 1 #数据中心ID，单范围：0-31

rocketmq:
  name-server: localhost:9876
  producer:
    group: mall-producer-group
    send-message-timeout: 10000

#spring:
#    application:
#        name: spring-boot-redis
redis:
  host: localhost
  port: 6379
  timeout: 20000
  password: 1116ABCabc1111
  database: 9
  #        cluster:
  #            nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
  #            maxRedirects: 6
  pool:
    max-active: 100
    min-idle: 10
    max-idle: 20
    max-wait: -1
---

redisson:
  address:  redis://localhost:6379
  password: 1116ABCabc1111
  database: 9
  timeout: 5000
  connectionPoolSize: 100
